branch-defaults:
  default:
    environment: udagram-api2-dev2
    group_suffix: null
deploy:
  artifact: www/Archive.zip
environment-defaults:
  node-typescript-psql-env:
    branch: null
    repository: null
  udagram-api2-dev:
    branch: null
    repository: null
global:
  application_name: udagram-api2
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
